Update to 21.04
NethServer/nethserver-ejabberd pull request #41
Opened 2021-05-18 16:26 UTC by stephdl

Time to update to 21.04, it seems there is no breaking changes this time

2021-05-18 21:32 UTC, jookk commented
Upgrade successful, working fine

2021-05-19 06:45 UTC, gsanchietti requested changes
Did you test BOSH integration with WebTop?

2021-05-19 06:45 UTC, gsanchietti commented on nethserver-ejabberd.spec
> +- Ejabberd: upgrade to 21.04 - NethServer/dev#6108
Please revert this change.

2021-05-19 13:21 UTC, stephdl commented
> Did you test BOSH integration with WebTop?

@gsanchietti i did not test it, what is supposed to do ?

2021-05-19 13:38 UTC, gsanchietti commented
You can create 2 webtop users and see if they can exchange messages from within webtop itself. See https://docs.nethserver.org/en/v7/webtop5.html#chat-integration

2021-05-19 13:49 UTC, stephdl commented
In the meanwhile I was looking to https://docs.nethserver.org/en/v7/webtop5.html#audio-and-video-webrtc-calls-with-chat-beta

2021-05-19 14:26 UTC, stephdl commented
The conversation with ejabberd and users in webtop is fine, the only things broken is the groupchat but this is true also with the 20.03 version

![Screenshot - 2021-05-19T162254 340](https://user-images.githubusercontent.com/3164851/118829918-d9110380-b8be-11eb-9530-bc5951de18b9.png)
![Screenshot - 2021-05-19T162202 282](https://user-images.githubusercontent.com/3164851/118829927-d9a99a00-b8be-11eb-9a7a-7b0ac24882ef.png)

see [gist](https://gist.github.com/stephdl/367f9fee51d13e9e08430273131612c2) for log information (20.03 version of ejabberd)

2021-05-20 13:32 UTC, stephdl commented on nethserver-ejabberd.spec
> +- Ejabberd: upgrade to 21.04 - NethServer/dev#6108
this is done

2021-05-20 13:36 UTC, stephdl commented
do we release it now or with a minor centos update ?

2021-06-24 13:34 UTC, stephdl commented
Let's wait another request from the community, there is not much interest

2021-06-24 13:34 UTC, closed without merging